services:
  - type: web
    name: portfolio
    env: java
    plan: free
    branch: master
    buildCommand: ./mvnw clean install
    startCommand: java -jar target/*.jar
    envVars:
      - key: PORT
        value: ${PORT}
